Fix shellcheck warnings

diff --git a/pre_commit/resources/hook-tmpl b/pre_commit/resources/hook-tmpl
--- a/pre_commit/resources/hook-tmpl
+++ b/pre_commit/resources/hook-tmpl
@@ -15,6 +15,6 @@ if [ -x "$INSTALL_PYTHON" ]; then
 elif command -v pre-commit > /dev/null; then
     exec pre-commit "${ARGS[@]}"
 else
-    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
+    echo "\`pre-commit\` not found.  Did you forget to activate your virtualenv?" 1>&2
     exit 1
 fi
